"""add core schema

Revision ID: c6d1649d0f20
Revises: 0001_empty_baseline
Create Date: 2026-08-30 17:01:38.322515
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'c6d1649d0f20'
down_revision = '0001_empty_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_chapters', sa.Integer(), nullable=False),
    sa.Column('style_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('arc_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_chapter', sa.Integer(), nullable=False),
    sa.Column('end_chapter', sa.Integer(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conflict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_chapters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arc_plan_end_chapter'), 'arc_plan', ['end_chapter'], unique=False)
    op.create_index(op.f('ix_arc_plan_novel_id'), 'arc_plan', ['novel_id'], unique=False)
    op.create_index(op.f('ix_arc_plan_start_chapter'), 'arc_plan', ['start_chapter'], unique=False)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goals', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('behavior_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_start_chapter', sa.Integer(), nullable=True),
    sa.Column('expected_end_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'name')
    )
    op.create_index(op.f('ix_character_novel_id'), 'character', ['novel_id'], unique=False)
    op.create_table('foreshadow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planted_chapter', sa.Integer(), nullable=False),
    sa.Column('expected_payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('payoff_chapter', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreshadow_novel_id'), 'foreshadow', ['novel_id'], unique=False)
    op.create_index(op.f('ix_foreshadow_planted_chapter'), 'foreshadow', ['planted_chapter'], unique=False)
    op.create_table('planning_blueprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('main_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ending', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('core_conflicts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('themes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_blueprint_novel_id'), 'planning_blueprint', ['novel_id'], unique=False)
    op.create_table('plot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impact_levels', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_feedback_novel_id'), 'plot_feedback', ['novel_id'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'category', 'name')
    )
    op.create_index(op.f('ix_setting_category'), 'setting', ['category'], unique=False)
    op.create_index(op.f('ix_setting_novel_id'), 'setting', ['novel_id'], unique=False)
    op.create_table('toc_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plot_function', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number')
    )
    op.create_index(op.f('ix_toc_entry_chapter_number'), 'toc_entry', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_toc_entry_novel_id'), 'toc_entry', ['novel_id'], unique=False)
    op.create_table('chapter_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('arc_plan_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('events', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pov', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('characters', sa.JSON(), nullable=False),
    sa.Column('conflict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hook', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_facts', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arc_plan_id'], ['arc_plan.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number')
    )
    op.create_index(op.f('ix_chapter_brief_chapter_number'), 'chapter_brief', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_brief_novel_id'), 'chapter_brief', ['novel_id'], unique=False)
    op.create_table('character_appearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('role_in_chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'chapter_number')
    )
    op.create_index(op.f('ix_character_appearance_chapter_number'), 'character_appearance', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_character_appearance_character_id'), 'character_appearance', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_appearance_novel_id'), 'character_appearance', ['novel_id'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['chapter_brief.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number')
    )
    op.create_index(op.f('ix_chapter_chapter_number'), 'chapter', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_novel_id'), 'chapter', ['novel_id'], unique=False)
    op.create_table('chapter_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('character_state_changes', sa.JSON(), nullable=False),
    sa.Column('foreshadow_updates', sa.JSON(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number')
    )
    op.create_index(op.f('ix_chapter_summary_chapter_number'), 'chapter_summary', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapter_summary_novel_id'), 'chapter_summary', ['novel_id'], unique=False)
    op.create_table('generation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_input', sa.Integer(), nullable=False),
    sa.Column('token_output', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_run_chapter_id'), 'generation_run', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_generation_run_novel_id'), 'generation_run', ['novel_id'], unique=False)
    op.create_index(op.f('ix_generation_run_task_type'), 'generation_run', ['task_type'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('generation_run_id', sa.Integer(), nullable=True),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_run.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_chapter_id'), 'review', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_review_novel_id'), 'review', ['novel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_novel_id'), table_name='review')
    op.drop_index(op.f('ix_review_chapter_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_generation_run_task_type'), table_name='generation_run')
    op.drop_index(op.f('ix_generation_run_novel_id'), table_name='generation_run')
    op.drop_index(op.f('ix_generation_run_chapter_id'), table_name='generation_run')
    op.drop_table('generation_run')
    op.drop_index(op.f('ix_chapter_summary_novel_id'), table_name='chapter_summary')
    op.drop_index(op.f('ix_chapter_summary_chapter_number'), table_name='chapter_summary')
    op.drop_table('chapter_summary')
    op.drop_index(op.f('ix_chapter_novel_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_chapter_number'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_character_appearance_novel_id'), table_name='character_appearance')
    op.drop_index(op.f('ix_character_appearance_character_id'), table_name='character_appearance')
    op.drop_index(op.f('ix_character_appearance_chapter_number'), table_name='character_appearance')
    op.drop_table('character_appearance')
    op.drop_index(op.f('ix_chapter_brief_novel_id'), table_name='chapter_brief')
    op.drop_index(op.f('ix_chapter_brief_chapter_number'), table_name='chapter_brief')
    op.drop_table('chapter_brief')
    op.drop_index(op.f('ix_toc_entry_novel_id'), table_name='toc_entry')
    op.drop_index(op.f('ix_toc_entry_chapter_number'), table_name='toc_entry')
    op.drop_table('toc_entry')
    op.drop_index(op.f('ix_setting_novel_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_category'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_plot_feedback_novel_id'), table_name='plot_feedback')
    op.drop_table('plot_feedback')
    op.drop_index(op.f('ix_planning_blueprint_novel_id'), table_name='planning_blueprint')
    op.drop_table('planning_blueprint')
    op.drop_index(op.f('ix_foreshadow_planted_chapter'), table_name='foreshadow')
    op.drop_index(op.f('ix_foreshadow_novel_id'), table_name='foreshadow')
    op.drop_table('foreshadow')
    op.drop_index(op.f('ix_character_novel_id'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_arc_plan_start_chapter'), table_name='arc_plan')
    op.drop_index(op.f('ix_arc_plan_novel_id'), table_name='arc_plan')
    op.drop_index(op.f('ix_arc_plan_end_chapter'), table_name='arc_plan')
    op.drop_table('arc_plan')
    op.drop_table('novel')
    # ### end Alembic commands ###
